version: '3.8'

services:
  nacos-standalone:
    image: nacos/nacos-server:v3.1.0
    container_name: nacos-standalone
    restart: always
    ports:
      - "8018:8080"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./volumes/nacos/conf/application.properties:/home/nacos/conf/application.properties
      - ./volumes/nacos/logs:/home/nacos/logs
      - ./volumes/nacos/data:/home/nacos/data
    environment:
      - MODE=standalone
      - TZ=Asia/Shanghai
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=nacos-auth-key-2025
      - NACOS_AUTH_IDENTITY_VALUE=nacos-auth-val-8f7d2b9c
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - agent_start

networks:
  agent_start:
    driver: bridge